run_name: full_training_odd_good_order
p_type: piplus
dtype: float32
# Data
# data_path: /remote/gpu06/favaro/datasets/calo_challenge/piplus_data_1.hdf5
data_path: /pscratch/sd/p/pmtuan/ddsim/single_pion_discrete_coarse_hcal/trainset_flat_good_order.hdf5
# val_data_path: /pscratch/sd/p/pmtuan/ddsim/single_pion_discrete_validation_coarse_hcal/trainset_flat_good_order.hdf5 # /remote/gpu06/favaro/datasets/calo_challenge/piplus_data_1.hdf5
val_data_path: /pscratch/sd/p/pmtuan/ddsim/single_pion_discrete_clf_train_coarse_hcal/all_showers_flatten.h5
xml_path: /global/cfs/cdirs/m3443/usr/pmtuan/CaloINN/binning_pion_odd_coarse_hcal.xml
single_energy: null
width_noise: 5.0e-6
custom_noise: False
val_frac: 0.01
eps: 1.0e-10
xml_ptype: "pion"
eval_dataset: "1-pions"
u0up_cut: 3.5
u0low_cut: 0.0
pt_rew: 1.0
dep_cut: 600

# Training
lr: 1.e-5
max_lr: 1.e-4
batch_size: 2048
max_samples: 1000000

lr_scheduler: one_cycle_lr

weight_decay: 0.01
betas: [0.9, 0.999]
n_epochs: 1000
cycle_epochs: 800
save_interval: 50

# Architecture
n_blocks: 12
internal_size: 256
layers_per_block: 4
coupling_type: rational_quadratic
bounds_init: 18
permute_soft: False
permute_layer: False
num_bins: 10
dropout: 0.0
layer_norm: nn.BatchNorm1d
layer_act: nn.SiLU
bayesian: False
prior_prec: 5000
std_init: -15.0

sub_layers: [linear, linear, linear, linear]
norm: True
# Preprocessing
use_extra_dims: True
use_norm: False
log_cond: True
alpha: 1.0e-8
alpha_logit: 1.0e-6
