[project]
name = "caloinn-lightning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "freia>=0.2",
    "h5py>=3.11.0",
    "jsonargparse[signatures]>=4.48.0",
    "jupyter>=1.1.1",
    "lightning==2.6.1",
    "matplotlib>=3.7.5",
    "pandas>=2.0.3",
    "particle>=0.25.4",
    "pyyaml>=6.0.1",
    "scienceplots>=2.2.1",
    "scikit-learn>=1.3.2",
    "scipy>=1.10.1",
    "setuptools<70",
    "torch>=2.0,<3.0",
    "wandb>=0.24.2",
    "normflows>=1.7.3",
    "umap-learn"
]
